### ISSUE TITLE
Populate classes generated with pyecoregen

### ISSUE THREAD

**Issue by pablo-campillo** [pyecore/pyecore#118]
A quite big metamodel is created with Eclipse EMF.
Then a library is generated with **pyecoregen**.
With the library, models are created and serialized in JSON.
Question: How to import those models to the library classes.?
The problem is that if I mix classes generated programatically with the library and those generated from the import, there are issues such as:

`pyecore.valuecontainer.BadValueError: Expected type <class 'buildingmodel.structural.structural.StructuralElement'>, but got type FlatSlab with value <pyecore.ecore.FlatSlab object at 0x7f105b4e6588> instead for feature <EReference structuralelement: <class 'buildingmodel.structural.structural.StructuralElement'>> of <EClass name="FEMStructuralElement">`

I import the model this way (Is it required the metamodel if I have the library...?):

```
rset = ResourceSet()
rset.resource_factory['json'] = JsonResource
resource = rset.get_resource(URI('metamodel.ecore'))
mm_root = resource.contents[0]
rset.metamodel_registry[mm_root.nsURI] = mm_root
resource = rset.get_resource(URI('model.json'))
mesh_project = resource.contents[0]
```

Is it the right way? Please, how I can solve it?
Thank you very much!

**Comment by aranega** [comment]
Hi @pablo-campillo ,

Thank for you issue and sorry for the delay on the other issues you open, lately I'm really under my schedule for everything I need to do...

Regarding your issue here, I'm not sure I understand exactly, sorry about that :sweat_smile: . You're having a `ecore` metamodel designed in Eclipse/EMF, then you generate the Python code using `pyecoregen`. From here however, when you deserialize a json model, you have issues opening your model? I think I'm not sure about what you call the "library", is it a model that is an instance of your metamodel and that gathers some basic objects you want to be able to use in another model? Or is is another metamodel that is linked to your main metamodel? I'm sorry if I really misunderstood your problem.

Otherwise, regarding the registering of your metamodel in a resource set, there is basically three scenarios:

1. either you open your metamodel in a dynamic fashion (as you did in your snippet), in that case, you need to regiser it manually in a resource set so the deserializer can link informations that are in the serialized json to an instance of metamodel and create/link elements
2. you have the code of your metamodel generated by `pyecoregen` with no special option, you need also to register it in a resource set for the same reasons
3. you have the code of your metamodel generated by `pyecoregen` with a special option to automatically register it in a global registry, so when you import the code of your metamodel, it will register it in a special registry that is inherited by any resource set. In that case, you don't have to register it manually.

The last solution otherwise would be to access directly this global registry to register your dynamic metamodel in it directly. Doing that, all your resource set will inherit from this "registration":

```python
from pyecore.resources import global_registry

rset = ResourceSet()
rset.resource_factory['json'] = JsonResource
resource = rset.get_resource(URI('metamodel.ecore'))
mm_root = resource.contents[0]
global_registry[mm_root.nsURI] = mm_root

# From this point any new resource set will have mm_root registered
rset = ResourceSet()
resource = rset.get_resource(URI('model.json'))
mesh_project = resource.contents[0]
```

**Comment by pablo-campillo** [comment]
Hello,

Sorry, maybe I didn't explain properly. This issue is not related with the previous issue.

- I have just one static meteamodel that will not change and it was designed with Eclipse EMF
- I generate code with pyecoregen using the ecore file
- I use the previous code for creating instances and serilize them into a json file.
- Later, I want to deserialize this json file into the same classes of the code generated to keep working on it. 

According to your explanation, I think that my situation is the option 2 and my problem is that I don't know how to register the code generated by pyecoregen as a resource. I use the ecore file as resource because I don't know other way to register a resource. Is it explained in the documentation?

Thank you very much for your support!

**Comment by pablo-campillo** [comment]
I find out how to register the python module generated by pyecoregen! :-)

**buildingmodel** is my python module generated.

```python
import buildingmodel
rset = ResourceSet()
rset.resource_factory['json'] = JsonResource
rset.metamodel_registry[buildingmodel.nsURI] = buildingmodel  # The key point!
resource = rset.get_resource(URI('/tmp/mesh_project.json'))
mesh_project = resource.contents[0]
```

**Comment by aranega** [comment]
@pablo-campillo Thanks for the clarification! Indeed, you found the keypoint, perhaps it wasn't very clear in the documentation or perhaps I totally forgot to tell something about it... In any case I will add that or make it more explicit.
 Actually in  PyEcore, generated module are considered more or less equivalent of `EPackage` (you have access to `nsURI`, `nsPrefix` ...etc) and if you really need to access the `EPackage` instance from a generated module, you can use `eClass` (in your code, you can access then the instance of `EPackage` that describes your generated metamodel using `buildingmodel.eClass`)

Also, if you don't want to register your metamodel each time for each resource set, you can also generate it using the `--auto-register-package`  option with `pyecoregen`, this will automatically generate the code that register your metamodel in the global registry when you import it.

**Comment by pablo-campillo** [comment]
I think It will be useful to add an entry in the documentation explaining this explicitly.

The --auto-register-package is really handy! Thank you very much!
