### ISSUE TITLE
Empty instance list not serialized

### ISSUE THREAD

**Issue by BertVanAcker** [pyecore/pyecore#122]
Hello,

I'm running into issues when interfacing existing instance models. When adding an instance to the list of instances, the serialization into the XMI file does not always work. If the instance is added to an empty instance list, it does not work, if an instance is already present in the list, everything works fine. A small hack within the XMI file does solve the issue but is required for each instance type, which is not desired.

**Comment by aranega** [comment]
Hi @BertVanAcker ,

Thanks for the issue, it seems like a really critical behavior your found there! Could you provide a very small example to replicate the problem? I tried with this, but I wasn't able to:

```python
from pyecore.ecore import *
from pyecore.resources import ResourceSet

# Quick metamodel definition
eClass = EPackage('test', nsURI='http://test/1.0', nsPrefix='test')

@EMetaclass
class A(object):
    names = EAttribute(eType=EString, upper=-1)


@EMetaclass
class B(object):
    elements = EReference(eType=A, containment=True, upper=-1)
    refs = EReference(eType=A, upper=-1)


# model creation
a = A()
a.names.append('NameA')
b = B()
b.elements.append(a)
b.refs.append(a)


# resource creation
rset = ResourceSet()
resource = rset.create_resource('Z.xmi')
resource.append(b)
resource.save()
```

Here is the produced XMI:

```xmi
<?xml version='1.0' encoding='UTF-8'?>
<test:B xmlns:xmi="http://www.omg.org/XMI" xmlns:test="http://test/1.0" refs="//@elements.0" xmi:version="2.0">
  <elements names="NameA"/>
</test:B>
```

**Comment by aranega** [comment]
@BertVanAcker Thanks a lot for the minimal case using `InterfaceKB`. I didn't know this library, I'm happy to see that PyEcore is used as dependency of so interesting projects :). I look all of that asap and I keep you updated.

**Comment by aranega** [comment]
@BertVanAcker OK! I found the bug. The issue is actually not in PyEcore, but in the way `InterfaceKB` is handling PyEcore collections. From what I saw, InterfaceKB is directly handling the inner collection `items` of each `EOrderedSet` object. This inner collection is part of the implementation of `OrderedSet` provided by the `ordered_set` package and is not meant to be handled directly. The `OrderedSet` is actually doing some optimizations on the way it represents data and PyEcore is overriding those basic behaviors (`append`, `remove`,...) to deal with the containement relationship on objects, runtime type checking and so on. So a collection should only be handled like a normal one, not considering the inner structure/data of the collection. By passing over those behaviors, the `StopCondition` instances were connected to other object, but they were not considered really as "contained" by anyone. The XMI serialization mimic the one in EMF that states that if an object is not contained by no-one (not in a resource, not by any object), then they are not serialized, and this is what happened there.
I made some fix in InterfaceKB and with those, everything works as expected.

For example, in `ASGFunctions.py`, I changed line 299:

```python
# before
terminator_container.hasStopCriterion.items.append(terminator)

# after modification
terminator_container.hasStopCriterion.append(terminator)
``` 

There is equivalent fix that can be done in the same file at line 38, 40, 83, 123, 125, 168, 201.

The same kind of fix have to be done also in `KB_Interface.py` at many positions.

I would gladely propose the fix for `InterfaceKB`, but I don't have access to the source code repository :).

**Comment by BertVanAcker** [comment]
Hello,

Thanks for the quick respons! I did not know that there was this append function on the OrderedSet.
For the ASG, I got it to work! Thanks a lot!
For some other elements, this seems to resolve in the following BadValueError:

    pyecore.valuecontainer.BadValueError: Expected type <EClass name="StopCriterion">, but got type StopCriterion with value <pyecore.ecore.StopCriterion object at 0x00000208A9AF3940> instead for feature <EReference hasStopCriterion: <EClass name="StopCriterion">> of <EClass name="Terminator">

This occurs if the element is not an element of the root object, but an element of a parent connected to the root. This has an other relationship name in our ecore model, namely _hasStopcondition_ instead of _includesStopcondition_ so we made a seperate create function (create_NoPlatformRoot). For StopCondition, this seems to work correctly but not for all other elements. Is this error a known issue or will it be the inconsistency in the model part?

**Comment by aranega** [comment]
Hello,

I'm glad part of your project is now working :). Yes, `EOrderedSet/OrderedSet` has the same operations as `list` knows, they should implement almost all of them.

Regarding your other issue, it's hard to say, this could come from an inconsistency from the model part, it could come also from a "migration" from one metamodel to another (i.e: you are serializing a model with the version 6.1 of your metamodel, open it with this version again later, but try to add some elements of this model to a model built with version 7 of your metamodel), or, of course, it could also come from an issue in PyEcore. If you have a small example that triggers the error, I can look for the issue!

**Comment by BertVanAcker** [comment]
Hello,

I made an update on the API in order to demonstrate the `BadValue error`. 
If you run the following code with `triggerFault=True` , a productPart is added to Product (parent), which raises the `BadValue error`.

    from Interface_KB import KB_Interface,InterfaceObjects
    API = KB_Interface.KB_Interface(False)

    jsonPath = API.resolvePath('input/JSON-docs/addProductPart.json')
    interfaceObject = InterfaceObjects.ProductPart(jsonPath)

     path_ecore = API.resolvePath('input/metamodel/Version5/PACoMM.ecore')  # TODO: adapt to one version!!    #TODO: adapt to one version!!
     path_KB = API.resolvePath('input/KB_examples/test_addProductParts.pacopackage')
     API.KB_path = path_KB  # To update current KB
     API.ECORE_path = path_ecore  # To update current KB
     API.model = API.importInstanceModel(path_ecore, path_KB)

     # perform setter function
     error = API.setProductPart(interfaceObject,triggerFault=True)

I still have some problems with not serializing parts of the model. For example, below a product is annotated with a `Assembly Sequence` and in the code, I only use the `container.append()` instead of the `container.items.append()`. However, it is not serialized. If you debug the code, the assembly sequence is present (`API.model -> includesProduct -> hasAssemblySystem -> hasAssemblySequence`

    from Interface_KB import KB_Interface,InterfaceObjects
    API = KB_Interface.KB_Interface(False)

    # create an empty KB model
    API.createEmptyKB(Name="test_setAssemblySequence_empty", OutputPath="output/KB_Instance/")

    # load the json file to perform update
    jsonPath = API.resolvePath('input/JSON-docs/AssemblySequence.json')
    interfaceObject = InterfaceObjects.AssemblySequence(JSONDescriptor=jsonPath, DEBUG=False)

    path_ecore = API.resolvePath('input/metamodel/Version-6-1/PACoMM.ecore')
    path_KB = API.resolvePath('output/KB_Instance/test_setAssemblySequence_empty.pacopackage')  # TODO: make version where no Product is defined!
    API.KB_path = path_KB  # To update current KB
    API.ECORE_path = path_ecore
    API.model = API.importInstanceModel(path_ecore, path_KB)

    # updating the ASG model
    error = API.setAssemblySequence(AssemblySystemName="TEST_AS",InterfaceObject=interfaceObject)

    API.model = API.importInstanceModel(path_ecore, path_KB)
    InterfaceObject_received = API.getAssemblySequence("TEST_AS")

For what I can tell, the  `assembly sequence` element is both part of `PlatformRoot` and `AssemblySystem`, which is defined by a collegue of me who is not involved in the project now. Could that be the cause of the problems of not serializing?

**Comment by aranega** [comment]
Hi @BertVanAcker ,

I checked quickly what could be the issues, the two come from different sources (obviously). The problem you have with the `BadValueError` exception come from the fact that you are loading your metamodel many times at different times in different `ResourceSet`. As the metamodel is loaded many times, many metaclasses are created. In the first example that you sent, the first loading occurs from the `importInstanceModel`, you open the metamodel and register it as a dynamic instance, then, you open the model instance of this metamodel. Then, a second time the loading of the metamodel/store in another resource set and store as another dynamic metamodel is performed from the `setProductPart` (trigerring a `initialize` in `KB_Interface.py`, then the `HelperFunctions.py`). The same process occurs a second time, meaning that the model you loaded is still instance of the other metamodel (the one you loaded the first time), and PyEcore cannot consider the two metamodels loaded in two different resource set as the same one, that's why the error is triggered, your metamodel is loaded two times in memory. To overcome this issue, there is various ways: 

* you could share a unique resource set among the whole execution, this time, you would not have those problems;
* instead of registering the metamodel a second time to gain access, you can do it directly from the model you loaded. Each model/instance in a model as a relationship to its metamodel/metaclass. Consequently, if you have the root of your model or any element stored in a metaclass, you can retrieve its metamodel this way (considering the model element is in `x`): `x.eClass.ePackage`. From there, you can also access the resource set: `x.eClass.eResource.resource_set` or even `x.eResource.resource_set`.
* The last solution would be to register and use the `global_registry` from `pyecore.ecore.resources` that gives you access to a registry that is shared by all resource set, whenever you create it. Consequently, if you store a metamodel in there, it will be accessible from every resource set.

Regarding your second issue,  the problem comes from your metamodel, the `hasAssemblyMetric` relationship is not a containment relationship, and when you build the model, those elements are, at the end, without a resource. They are linked to the `AssemblySequence`, but they are not contained by this instance as the relationship is not set as a container. Consequently, the `AssemblyMetric` instance that you create is not "contained" by `AssemblySequence`, so it does not have a resource at the end, so it is not serialized by the XMI serializer as it doesn't know how to make a reference toward it (it cannot be an internal node, it cannot be a path toward a node inside of the xmi and it cannot be a cross-reference towards another resource). To fix this, either `hasAssemblyMetric` has to be defined as containement, or you need to build the container for the `AssemblyMetric` instances and to add it to the same model where you have your `AssemblySequence` instance.

**Comment by BertVanAcker** [comment]
Hello,

The hint of loading the metamodel multiple times did the trick! Thanks a lot for all the good help! 
The problem was not only caused by loading the metamodel a second time in the  `Initialize` functions, the resource set was actually loaded twice in the `importInstanceModel` function already. So the `Initialize` functions loaded it a third time,  which obviously is not good. This `importInstanceModel` function was a legacy function, assumed to be correct, therefore I did not take that into account while debugging.

Again, thank you so much for your help! This will speed up the project work :smiley:
