### ISSUE TITLE
Existing projects: http://agx.me/ ?

### ISSUE THREAD

**Issue by jean** [pyecore/pyecore#13]
Please pardon me if I'm off track, but is http://agx.me/ interesting?

**Comment by aranega** [comment]
Hi Jean,

Sorry I took so long, I wasn't aware of the AGX project, so I took a look. 

From what I saw (and understood),  AGX proposes a way to generate code from UML (and UML with profiles). The main goal is to speed-up application developement by generating code parts. 

Pyecore is more related to EMF, the idea is to provide a framework to develop tools that uses models by giving all the features that could be needed to handle metamodels and models (dynamic metamodels/reflection/XMI serialization/static metamodels). Code generation (beside the metamodel generation) is not the main purpose of EMF/PyEcore. 

What do you have in mind about PyEcore and AGX?

**Comment by moltob** [comment]
I'd actually give it yet another spin. AGX is a set of tools (including a bunch of Eclipse plugins) and code generators that generate various Python development artifacts targeting a number of frameworks and technologies like plone and buildout. The source for generation is UML. Since UML on its own is too general, profiles are applied, essentially creating DSLs for the target domains via stereotypes. This is the standard MDA approach.

Pyecore is just a Python implementation of EMF's Ecore meta-meta-model. As such it is at the same meta-level as OMG's MOF, which is the meta-model of UML. In the EMF world, you use much simpler meta-meta-models like MOF or Ecore to directly build DSL meta-models, instead of applying stereotypes to UML elements. With these meta-models, you can then do whatever you want. Unlike @aranega 's comment suggests, I am using Pyecore *mainly* for code generation, e.g.:

* Build a DSL metamodel, e.g. for a statemachine model, defining states, events and transition concepts.
* Generate the Python classes for this meta-model with pyecoregen.
* Build a code generator for statemachine models with pymultigen and Jinja2.

This is just an example. If you look at the Eclipse EMF universe, you'll find tons of applications of this direct metamodeling, which has proven to be very useful.

Personally, I prefer doing it this way, as the resulting models are usually easier to communicate compared to discussing stereotyped UML models.

**Comment by aranega** [comment]
I see this a little bit like Papyrus vs Sirius, where Papyrus would be a part of AGX and PyEcore more related to Sirius (more about the idea, not the tooling).

**Comment by jean** [comment]
@moltob @aranega wow, thanks for the incisive answers. 
I'm looking around for a way to generate XML from (quite simple) UML descriptions of the content in a CMS. This looks like the deep end, but very intriguing.

**Comment by moltob** [comment]
Wanted to quickly follow up, since I am not sure what you meant by the _deep end_. How and whether you would use pyecore all depends on how the UML model is represented (instantiated) in you CMS usecase. 

Do you already have Python classes for the different UML types like class or association? If so I don't think there is much gain in using pyecore, as it would allow you to build the UML metamodel you already have. Then, to generate XML from it I would probably use Python's etree library, i.e. use model-to-model (UML objects to etree nodes) transformation code to build the output DOM and then serialize to XML text using etree.

Alternatively, you could use the [pymultigen](https://github.com/moltob/pymultigen) project (basis for pyecoregen) to build a code generator for a model-to-text (UML objects to XML file) transformation. In that case you could write a Jinja2 (or any other kind of) template that essentially produces XML text as you want it.

Your UML class instances probably represent some form of business entities. You could use pyecore to model these entities and their relations and then generated XML from that, as described above.

If your UML model is not even in memory, but represented as text, you need to use a parser (or write one) to get a memory representation of it and then continue as above.

But when you say CMS, web applications usually come with their templating environments, so you can probably use that one directly to produce XML text from UML objects that are passed to the template's context. In that case, pyecore and agx would be overkill in my point of view.

Maybe this helps a bit, feel free to ask for more input in case you want to go a certain route.

**Comment by jean** [comment]
@moltob thanks again :-) It sounds like you enjoy this modelling stuff. 

> what you meant by the _deep end_.

As soon as there's more than one "meta" in play, it's deep, as far as I'm concerned.

> Do you already have Python classes for the different UML types like class or association?

No Python in the picture sadly. (Actually right now I'm generating XML from ad hoc YAML using Python `etree`, but my goal isn't Python-related.)

> Alternatively, you could use the pymultigen project (basis for pyecoregen) to build a code generator for a model-to-text (UML objects to XML file) transformation.

This sounds good. 

> Your UML class instances probably represent some form of business entities.

Yes, exactly.

> If your UML model is not even in memory, but represented as text, you need to use a parser (or write one) to get a memory representation of it and then continue as above.

Yes. The starting point that I'm currently looking at is PlantUML or YUML format for plaintext representation of UML. 

This fulfils two main goals: 

- it gets us a compact plaintext representation with only the salient details and no boilerplate code, checked into version control, and, as a nice extra,
- pretty diagrams, easily shareable on the web, with an interesting range of tool support. 

I don't want to foist any big UML editor onto our company, which currently doesn't use UML in any way shape or form.
I just want to write down our content types in a less ad hoc manner than YAML.

This led to the thought that if I'm going to be parsing PlantUML text, it's probably better to transform it to XMI, and then do a transformation from XMI to Orchard XML. 
Because then I could build on existing XMI tooling, and play with big UML editors too.
I'm not yet sure that this is really a good idea.

> But when you say CMS, web applications usually come with their templating environments,

My specific goal is to generate XML representing content type definitions for the Orchard CMS to import. The Orchard import format is flexible, allowing me to define new types and parts, or to customize standard ones, with all their fields, widgets, and relationships defined, and also to define "parts". Parts are similar to interfaces. They add fields and configuration to the content types where they are assigned, and can trigger behaviour (e.g. add a `CommentPart` and people can comment on your new type).

**Comment by aranega** [comment]
@jean @moltob Wow, I'm just coming back from few days off and what a pleasant discussion for a monday morning :-)

From what I understand, you try to use as much as possible an existing domain to gain access to various existing tools around plantUML (and UML). As Mike exposed to you, there is many ways to achieve your goal, the way you choose depends on what you really want to handle at some point. You could simply use:

    .plantuml --[PlantUML parser]--> CST (or AST depending on your parser result) --[pymultigen]--> Orchard XML

You could also decide to use an intermediate UML-XMI representation:

    .plantuml --[PlantUML parser]--> CST/AST --[Python + PyEcore]--> UML-XMI --[pymultigen]--> Orchard XML

That latter solution gives some flexibility if you need to perform some validations or to modify/transform your UML-XMI (using PyEcore or any XMI friendly tool), but the creation of the UML-XMI representation from the CST can be tedious. It really depends on your parser result actually.

Following this latter solution, if UML is not a requirement, you could also define your own metamodel instead of UML (closer to your domain):

    .plantuml --[parser]--> CST/AST --[Python + PyEcore]--> DSML-XMI --[pymultigen]--> Orchard XML

This approach does not allow you to use UML compatible tools, but you can still use existing tools that can handle XMI and metamodels at the end (QVT, Epsilon, ...).

In facts, all depends on: do you need an intermediate representation or not (for these kind of solutions).
