### ISSUE TITLE
New version breaks serialization of $ref's in pyecoregen-generated metamodel

### ISSUE THREAD

**Issue by alessiostalla** [pyecore/pyecore#130]
It's hard for me to create a minimal reproduction case, but it seems like that version 0.13.0 serializes my metamodel incorrectly, with empty class $ref's, like so:

```
+                    'eSuperTypes': [{'$ref': '',
-                    'eSuperTypes': [{'$ref': '#//PossiblyNamed',
```

This is an excerpt of the comparison of my metamodel with the previous version 0.12.2, as dicts loaded from JSON. It happens for all references to EClasses, not just supertypes.

This is the relevant test code: https://github.com/Strumenta/pylasu/blob/27d1ca1aab36bf6fddfd70a9ba34c55521daae95/tests/test_metamodel_builder.py#L87-L96

The reference JSON file is the one generated by the previous pyecore version, already patched to replace EDataType references from a `#//String` pattern to a `ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString` pattern that pyecore 0.13.0 is producing.

**Comment by alessiostalla** [comment]
It looks like 0.13.0 breaks $ref always when serializing. Check the following test case:
https://github.com/Strumenta/pylasu/blob/669d32aff66469a2a06a48775617dbf7ea4de55a/tests/test_metamodel_builder.py#L100-L122

**Comment by aranega** [comment]
Hi @alessiostalla,
Thanks for the following on the issue. I'm deeply sorry I took so much time to anser, the notifications for those points were drawn in a sea of notifications I received few month back, I totally missed them.

I'll investigate a little bit more all of this quickly. I don't know why the `$ref` would be broken, I don't remember I changed something in the model serialization/deserialization and the test I have are passing. It means that there is probably just a simple case or a corner case that I'm not handling properly in the tests.

**Comment by aranega** [comment]
Hi @alessiostalla,

I had a little bit of time to check the `$ref` issue. The issue was coming from a bug in the way `eResource` is computed for static metamodels, as well as a small misuse of the `Resource` API in your test.

So, what was happening? I actually made some modification on the `JsonResource` that I totally forgot about. I actually harmonized/simplified the way the relations are computed for each element. Before, it was a specific dedicated computation that was building the object URI fragment. I changed that to use the exact same function that built the URI fragment for the xmi resource. However, a miscomputation of the `eResource` of each element lead to the fact that the resource thought the object wasn't contained in any resource. Consequently, it discarded it from the serialization as EMF does.

I introduced a new link between the dynamic and static world to fix that. In the future, it will be also helpful to smooth some part of the API.

However, even with that fix, your test were not passing for a small misuse of the API to add elements to the resource. That's one of the few points that diverges from the EMF implementation. Unlike EMF, you should not access to the content of the resource to add an element, but you need to directly add an element to the resource.

This means that in https://github.com/Strumenta/pylasu/blob/669d32aff66469a2a06a48775617dbf7ea4de55a/tests/test_metamodel_builder.py#L110

you shouldn't do

```python
resource.contents.append(mb.generate())
```

but instead:

```python
resource.append(mb.generate())
```

The `append(...)` method actually performs some eContainer-like operations on the object to attach it to a resource and consider a parent to it.

So there's a fix now on `develop` that should fix the issue with this, and as side-effect, the modifications I made for 0.13.0 should also fix the issue you had with the `EEnum`. I checked in depth the generated code, the code is correctly generated, there is no problem on it. As you spotted the second `for...` iterating on values is redundant, but causes no harm. I'm not 100% certain, but I think the issue you had came from the URI fragment computation. I tested the current version and I had no issue with the serialization of your metamodel.

I'll perform few other cheks and I'll release a new version `0.13.1` with this fix.

**Comment by alessiostalla** [comment]
Thanks!!

**Comment by alessiostalla** [comment]
I can confirm it now works with 0.13.1, thanks a lot!
