### ISSUE TITLE
deserialize UTC datetime string to EDate

### ISSUE THREAD

**Issue by TerryKingston** [pyecore/pyecore#25]
hello aranega,

I'm not sure of the property way to use pyecore to deserialize datetime values from an XMI resource. I constructed an XMI resource using an ecore metamodel and set an attribute to datetime.utcnow(). the resource serialized without issue using `resource.save()` but upon loading the resource using `create_resource` I get the following error:

```
>>> resource = rset.get_resource(URI(inFilePath))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/lib/python3.5/site-packages/pyecore/resources/resource.py", line 82, in get_resource
    resource.load(options=options)
  File "/env/lib/python3.5/site-packages/pyecore/resources/xmi.py", line 46, in load
    modelroot = self._init_modelroot(root)
  File "/env/lib/python3.5/site-packages/pyecore/resources/xmi.py", line 113, in _init_modelroot
    self._decode_eattribute_value(modelroot, feature, value)
  File "/env/lib/python3.5/site-packages/pyecore/resources/xmi.py", line 128, in _decode_eattribute_value
    eobject.__setattr__(eattribute.name, val)
  File "/env/lib/python3.5/site-packages/pyecore/ecore.py", line 582, in __set__
    instance_dict[name]._set(value)
  File "/env/lib/python3.5/site-packages/pyecore/valuecontainer.py", line 73, in _set
    self.check(value)
  File "/env/lib/python3.5/site-packages/pyecore/valuecontainer.py", line 46, in check
    raise BadValueError(value, self.feature.eType)
pyecore.valuecontainer.BadValueError: Expected type <pyecore.ecore.EProxy object at 0x10d5c0048>, but got type str with value 2018-06-05 16:15:47.290839 instead
```

myMetamodel.ecore
```xml
...
<eStructuralFeatures xsi:type="ecore:EAttribute" 
    name="documentRevisionDate" 
    eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
...
```

mySerializeData.xmi
```xml
... 
documentRevisionDate="2018-06-05 16:15:47.290839"
...
```

It also failed to deserialize using a timestamp and timestamp string. please help me understand the property way to serialize/deserialze datetime values. 

Thanks for this amazing project,

**Comment by aranega** [comment]
Hi @TerryKingston 

Oopsy, that's definitely an issue in PyEcore, you are doing everything the right way!

PyEcore uses two methods for the `EDatatype` instances serialization: 

* `from_string` for deserialization (parsing a string)
* `to_string` for serialization (you can control the output format)

By default, it uses the string representation of an object for the serialization and it sets the read value as attribute value during deserialization. That's the problem here, the `EDate` time misses a proper `from_string` implementation. 

I will put a fix asap on the `develop` branch for the next version, in the meantime, you can monkeypatch the `EDate` datatype to fix this issue like this in your script:

```python
from datetime import datetime
from pyecore.ecore import EDate

EDate.from_string = lambda s: datetime.strptime(s, '%Y-%m-%d %H:%M:%S.%f')
```  
I know this is not ideal, but at least you should not be blocked until the next release.

**Comment by TerryKingston** [comment]
aranega,

Thanks for the quick response, that temp fix seems very reasonable, I'll add it to my code and get back to you if I encounter any issues.

**Comment by aranega** [comment]
@TerryKingston I had time today to provide a new PyEcore version with the fix for `EDate` (among others). You can `pip install pyecore -U` your local version!

**Comment by TerryKingston** [comment]
aranega,

ran `pip install pyecore -U` and now UTC date strings are deserializing correctly. 

Thanks!

**Comment by aranega** [comment]
I'm glad it works well for you :). Thanks again for the report!
