### ISSUE TITLE
pyecore's eorderset can't work under ordered-set 3.0.0

### ISSUE THREAD

**Issue by CFAndy** [pyecore/pyecore#28]
@aranega 
 It might be a regression. 
 ordered-set 3.0.0 change the slicing implementation 
from 
```python
               return OrderSet(result) #2.0.2
```
to 
```python
               return self.__class__(result) # 3.0.0
```
and the slicing will return EOrderedSet with empty items.
for 
```python
              Node.children[1:]
```
Could you give a check ?

**Comment by aranega** [comment]
@CFAndy I will check this asap! Thanks a lot for the report, I guess I'm good for a new release again :-)

**Comment by aranega** [comment]
@CFAndy Indeed, that line is part of the issue. I manage to go over it, but, there is another issue related to the fact that when a slice is asked to an `EOrderedSet`, with the modification made in `OrderedSet`, it tries to return a new `EOrderedSet`. In a pure logical way, it should be fine as the modification had been made in order to properly deal with subclassing, but in PyEcore's case, it is not so great as each "collection" owns information from the owner and the feature related to the collection. This behavior is here in order to get information "at the source" for the notification system. Unfortunately, when the new collection is built, the `OrderedSet` does not know about these extra parameters and cannot pass them during the new sublist init.  

But, in a way, the fact to get a new `EOrderedSet` if you ask for a slice on it is not so great as it would imply that the sublist (which is a copy) is related to the original owner and feature, which is a little bit weired for a copy in PyEcore context.
Finally, the old behavior of the `OrderedSet` object was great in "slice cases" as it returned a copy from the original object the `ECollection` mimic the behavior from (e.g: for an `EList`, a slice returns a `list` which sounds kinda logical).

I made some modification in order to replicate the new behavior while letting the opportunity to change it on demand.  In `ordered_set_patch.py` I patched `OrderedSet` to add a new method named `subcopy` and I patched the original `__getitem__` method like this:

```python
# In 'ordered_set_patch.py'
def __getitem__(self, index):
    if index == ordered_set.SLICE_ALL:
        return self.copy()
    elif hasattr(index, "__index__") or isinstance(index, slice):
        result = self.items[index]
        if isinstance(result, list):
            return self.subcopy(result)  # Changed from self.__class__(...) to self.subcopy(...)
        else:
            return result
    elif ordered_set.is_iterable(index):
        return self.subcopy([self.items[i] for i in index])  # Changed from self.__class__(...) to self.subcopy(...)
    else:
        raise TypeError("Don't know how to index an OrderedSet by %r" % index)


def subcopy(self, sublist):
    return self.__class__(sublist)

ordered_set.OrderedSet.__getitem__ = __getitem__
ordered_set.OrderedSet.subcopy = subcopy
```

This modification does not alter the original behavior, but it let me the opportunity to change it in the `EOrderedSet` implementation from the `valuecontainer.py` like this:

```python
# In 'valuecontainer.py'
class EOrderedSet(EAbstractSet, ordered_set.OrderedSet):
    # '__init__' and 'update' methods here

    def copy(self):
        return ordered_set.OrderedSet(self)

    def subcopy(self, sublist):
        return ordered_set.OrderedSet(sublist)
```

This way, the original `OrderedSet` behavior is preserved while it can be overriden for the `EOrderedSet` class only. The first test I have about this works perfectly, but I have to check some corner cases first.

I know this modification is not ideal, but it will do the work. The best solution would be to drop the `ordered-set` dependency and add a dedicated `OrderedSet` for PyEcore.

**Comment by aranega** [comment]
@CFAndy I had time this lunch to write new tests and check if the issue is solved. It looks like the patch I made on `OrderedSet` works as intended, so I released a new version, PyEcore jumps to `0.8.5`.

Regarding the modification I pointed in the previous post, I also modified this line from the original implementation: 

```python
return self.subcopy([self.items[i] for i in index])
```
to use a generator expression, which should be will be more effective in memory:

```python
return self.subcopy(self.items[i] for i in index)
```

Could you tell me if this new version works for you? (it should, but... you never know)

**Comment by CFAndy** [comment]
@aranega 
Simply tested it and it works great! 
But I didn't go through your code carefully. I'll check it tomorrow.

**Comment by aranega** [comment]
@CFAndy Thanks! Hopefully, new version of the lib will not introduce more unexpected behaviors!

**Comment by bmjjr** [comment]
Hi, just wanted to file a report that on both current master and develop, I found I must pin ordered-set==2.0.2 to pass the test suite.  Otherwise if I use any >=3.0 version, the below 10 tests fail.  All the failing tests have the same problem on pyecore\utils.py line 74. 
```
tests\xmi\test_xmi_deserialization.py:140 (test_ecoreinheritance_loading)
def test_ecoreinheritance_loading():
        rset = ResourceSet()
        ecore_file = path.join('tests', 'xmi', 'xmi-tests', 'EcoreInheritance.ecore')
        resource = rset.get_resource(URI(ecore_file))
        root = DynamicEPackage(resource.contents[0])
        assert Ecore.EModelElement.eAnnotations in root.A.eAllStructuralFeatures()
        a = root.A()
        assert isinstance(a, Ecore.EModelElement)
        assert Ecore.EModelElement.eAnnotations in root.B.eAllStructuralFeatures()
        b = root.B()
        assert isinstance(b, Ecore.EModelElement)
>       assert a.eAnnotations == {}

tests\xmi\test_xmi_deserialization.py:152: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\ProgramData\Miniconda3\envs\pythonocc\lib\site-packages\ordered_set.py:298: in __eq__
    if isinstance(other, (Sequence, deque)):
C:\ProgramData\Miniconda3\envs\pythonocc\lib\abc.py:193: in __instancecheck__
    return cls.__subclasscheck__(subclass)
C:\ProgramData\Miniconda3\envs\pythonocc\lib\abc.py:228: in __subclasscheck__
    if issubclass(subclass, scls):
pyecore\utils.py:74: in pyecore_issubclass
    return old_issubclass(self, cls)
C:\ProgramData\Miniconda3\envs\pythonocc\lib\abc.py:228: in __subclasscheck__
    if issubclass(subclass, scls):
pyecore\utils.py:74: in pyecore_issubclass
    return old_issubclass(self, cls)
C:\ProgramData\Miniconda3\envs\pythonocc\lib\typing.py:1154: in __subclasscheck__
    return super().__subclasscheck__(cls)
C:\ProgramData\Miniconda3\envs\pythonocc\lib\abc.py:228: in __subclasscheck__
    if issubclass(subclass, scls):
pyecore\utils.py:74: in pyecore_issubclass
    return old_issubclass(self, cls)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = typing.MutableSequence[~T], cls = <class 'dict'>

    def __subclasscheck__(self, cls):
        if self.__origin__ is not None:
            if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
>               raise TypeError("Parameterized generics cannot be used with class "
                                "or instance checks")
E               TypeError: Parameterized generics cannot be used with class or instance checks

C:\ProgramData\Miniconda3\envs\pythonocc\lib\typing.py:1148: TypeError
```

![failed-tests-1](https://user-images.githubusercontent.com/526707/50583604-2d111e00-0ea5-11e9-99e5-6f32587cdc72.jpg)

**Comment by aranega** [comment]
Hi @bmjjr

Thanks a lot for your ticket! I think you probably put your finger on the root of the issue opened by @CFAndy (issue #47). 
The temporary solution was to  upgrade the Python version, but if the problem can be reproduced playing with ordered-set version, that's awesome!
I'll work on it right away to find why it introduces such an error. I hope I will find a solution soon.
Thanks a lot for your patience and sorry for the inconvenience...

**Comment by aranega** [comment]
Ok, so the issue seems to come from Python's `typing` module. The introduction of some type check in the `ordered_set` module triggered the typing issue.

I close again this issue :). Thanks so much @bmjjr for the test case, it gave me more material to reflect on!
