### ISSUE TITLE
Inheritance in PyEcore

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#60]
Hi @aranega 

I'm experimenting with inheritance and behaviour in PyEcore.
I'm trying to create subtype of a certain class by doing:
``` python
CommercialBuildingMetaClass = EClass('CommercialBuilding', superclass=(esdl.Building.eClass))
CommercialBuilding = CommercialBuildingMetaClass(name = 'CommercialBuilding')
c = CommercialBuilding('A CommercialBuilding')
```
So CommercialBuilding should be a subclass of Building, but it does not inherit its attributes, nor the EOperations. If i print the attributes of c it only shows the name attribute, not the inherited ones.
If i add behavior to the esdl.Building class, it also does not get inherited to the subclass.
E.g.:
```
esdl.Building.eOperations.append(EOperation(name='test'))
@esdl.Building.behavior
def test(self):
    print('Hi {}'.format(self.name))
...
b = esdl.Building('A Building')
b.test() # prints "Hi A Building"
c.test() # Throws an error
```
What am I doing wrong? How should inheritance work in PyEcore?

**Comment by aranega** [comment]
Hi @ewoudwerkman 

The inheritance in PyEcore should be straight forward. In your case, from what I understand from your code, you are actually extending the Ecore metamodel and not your metamodel. I'm the one to blame for this, I use the same name: `eClass` to deal with two concepts and it can be confusing. This attribute is used to go from the static eclass world to the dynamic counterpart, but if you are in the dynamic eclass world, it is used to find its actual metaclass.

In your case, I undestand that you are dealing with Dynamic `EClass`, and that `esdl.Building` is a dynamic `EClass`. In that case, this line does not extend the `Building` EClass, but extends the metaclass of the `Building` EClass (you are actually subclassing `EClass`).

```python
CommercialBuildingMetaClass = EClass('CommercialBuilding', superclass=(esdl.Building.eClass))
```
In your case, as you are dealing with dynamic EClass, your call should be changed like that:

```python
CommercialBuilding = EClass('CommercialBuilding', superclass=(esdl.Building))
c = CommercialBuilding('A CommercialBuilding')
```
I know that it the bridge between the dynamic and static part can be confusing because of the design I used. I will try to smooth everything in future versions. You can find deeper information about that and how the two worlds are related in this picture:

![PyEcore Metaclasses System](https://modeling-languages.com/wp-content/uploads/2017/02/img_58993c2977676.png)

And more in depth details on this blog post: https://modeling-languages.com/pyecore-python-eclipse-modeling-framework/

I will try to smooth things up and update the documentation accordingly for next versions.

**Comment by ewoudwerkman** [comment]
Ah, thanks! That clarifies things. Now it works as expected!

**Comment by aranega** [comment]
@ewoudwerkman I'm glad it works for you :) !
