### ISSUE TITLE
Python-based code generator

### ISSUE THREAD

**Issue by moltob** [pyecore/pyecore#9]
While the provided option of using the Acceleo-based generator is terrific, in particular since you can use genmymodel instead of Eclipse, I'd like to see a programmatic (and Python-based) option as well. This would be even more approachable by the Python community and can be greatly integrated into the automatic test-suite, which is not really possible with genmymodel etc., in particular in an offline test scenario.

You already agreed a number of times that this would be a useful feature. Please let me know whether you have this on the agenda already (maybe it's even almost done), or whether this would be a good thing for me to offer as contribution. Obviously this is a bit more work than tuning a few MTL template features and I would mainly doing this in private time, so it'll take a bit. Just want to make sure you generally share my view this is useful and did not do it yet.

If so, we'll use this ticket for discussion about things I might have to ask or get your opinion on. I'd design the generator in an extensible way, so we can ship a built-in one reproducing the current MTL-generated code, but users should be able to hook in their own templates as well to produce whatever they want.

Let me know.

**Comment by aranega** [comment]
Indeed, I still believe this is a terrific idea and it would be awsome to be able to quickly generate/re-generate on the fly the metamodel code. This is a feature that is on the roadmap for sure, but I only check some templating engines, nothing more, I haven't started it (just experimenting with Python 3.6 f-strings, but the result wasn't very flexable nor close from MTL-Acceleo, which was the goal I was trying to reach). So, to sum up, I still greatly support the idea and I didn't do it nor started it. Thank you so much to taking time to improve the project!

Which template engine do you have in mind? I'm really not aware of the features offered by them and which one would be the best match.

Once again Mike, thank you so much for this!

**Comment by aranega** [comment]
The model to AST transformation looks like a lot of fun but, indeed, quite hard to maintain/extend. Also, I would add that the PyEcore + Jinja2 solution could also be used, in the same idea, to generate source code in other languages.

 
If this solution is flexible enough, perhaps it could be relevant to produce a little layer on top of Jinja to ease multiple files generations?

**Comment by moltob** [comment]
Maybe, but honestly, I don't think there is a lot of demand for this. Most projects seem to maintain a single template file per output file (plus reused templates), which is quite natural. I'll try without first. Let me see where this goes, we can improve and refactor afterwards, once we have a few basics in place.

**Comment by aranega** [comment]
Sure, basics first, of course, I was more thinking to future improvement if a general schema can be extracted from the code. 

I don't think either that there is a strong demand for multiple file generation in a general cases, but I was more refering to a extra-layer to provide a nice M2T facilities to PyEcore (and PyEcore only). As XMI is supported, a model could be produced with any editor (I think about a UML model, SysML or any other model from any EMF metamodel), exported as XMI and any code for this dedicated model could be easily generated.

**Comment by moltob** [comment]
Oh, totally! I misread your suggestion to extend Jinja on its own. But adding this as part of PyEcore makes total sense. I'll plan on providing a few decorators that should handle this as well as dispatching generator calls. I'll keep you posted once I get going.

**Comment by moltob** [comment]
Just sending an alive... I am still pursuing this, as I eventually need it for my projects. Just a bit short on time. Stay tuned.

**Comment by aranega** [comment]
No problem Mike, don't worry ;) thanks so much for doing this!

**Comment by moltob** [comment]
The generator branch is coming along. Need a few more train rides though... :-) One question: I am starting to generate the package `__init__.py` file and found the following at the top of the MTL template:

```mtl
[if (p.eSuperPackage = null)]
[let containingTypes : Sequence(EClassifier) = p.eAllContents(EReference).eContainingClass]
[for (sub : EPackage | p.eAllContents(EPackage))]
from [sub.qualifiedName().replaceAll('^[^.]+', '')/] import [p.eAllContents(EReference).eType->union(containingTypes)->select(ePackage = sub).name->asOrderedSet()->sep(', ')/]
[/for]
[/let]
[/if]
```

I think what this does is to import classes from subpackages into this package's namespace. The question is about the generated class set. I think what you're building here is (per sub-package) a list of classes in this sub-package, that are a referenced type or holding a reference, throughout the complete hierarchy of packages.

Could you explain the motivation? This seems to import way to many classes, as I would initially expect you need to import only reference types from other packages to allow compiling this package... On the other hand you don't seem to simply import all classes from all subpackages.

Thanks for shedding some light for me.

**Comment by aranega** [comment]
That's really a great news about the generator! I can't wait to see that and the related framework in action! I'm pretty sure this will mark a corner stone and interest many peoples.

Regarding the snipet for the `__init__.py`, the imports are only built for the root `EPackage`, not each sub-packages to avoid complex relative module referencement. 
The only project I have generated with many subpackages is the PyGeppetto project and if you look at the root [`__init__.py`](https://github.com/openworm/pygeppetto/blob/master/model/__init__.py), you'll see that all the imports are done in this package and not in the sub-ones.

Also, if you look at each `EReference` definition, they never directly defines the `eType` they are linked to. This task is also perfomed in the root `__init__.py` in order to easily deal with `eOpposite` relationships. In the `__init__.py` each class that owns a `EReference` must be accessed, and the reference `eType` must be assigned:

```Python
# For example
GeppettoModel.variables.eType = Variable
``` 
In this example, to do so, I need to import the `GeppettoModel` (that have been computed in the `[let containingTypes : Sequence(EClassifier) = p.eAllContents(EReference).eContainingClass]` statement) then all the `eType` they are linked to: `Variable` in this example (computed using: `[p.eAllContents(EReference).eType (....)/]`).

I don't know if this is more clear for you (I can try to rephrase if this is not), but at the end, the only goal was to ease the module dependency computation in Acceleo, by simply... removing it and puting everything in the root `__init__.py`. With this snippet, only the types involved in the relationship and the type owning the relationship are imported. Now I write it, perhaps using a kind of fully qualified path towards each resource is enough and could avoid that?

**Comment by moltob** [comment]
Thanks a lot. That does explain it. Once this is all working smoothly we can try to improve the generated code if needed. But that really should wait until the generator works within the CI. So for now I just copy the MTL logic and try to understand what you've done there. Thanks again.

**Comment by moltob** [comment]
Thanks for the merge and the new repo. I started the move this morning and will push during the weekend, I hope. I'll let you do the pypi registration for pyecoregen. I'll do it for the base library.

**Comment by moltob** [comment]
Quick update:
* removed pygen from pyecore (on my fork of develop)
* added pymultigen project for the multifile facade
* moved ecore specific generation stuff to pyecoregen
* all unit tests running

Next steps:
* I'll set up Travis CI and coverage measurement for pymultigen.
* I'll publish pymultigen to PyPI.
* We can then set up Travis and PyPI publishing for pyecoregen. I can prepare this but I should probably leave the PyPI publish step to you, as the organization is yours... :-)
* Once both packages are available on PyPI, I'll push my pyecore changes to develop.

**Comment by aranega** [comment]
Noted for all the points, I wait for the Travis configuration and the pymultigen publishment, and I will publish pyecoregen on pypi :-). 

I will probably release a new pyecore version when everything will be published to pypi and communicate over pymultigen and pyecoregen. Is that ok if I thank you nominatively on twitter - with perhaps a link towards your personal github page - about your help/contribution/work on pyecore/pyecoregen? (just for the record, I'm terrible at all the communication stuffs, but I try anyway).

Thanks a lot Mike! I can't wait to integreate pyecogen as part of the build process for new pyecore related projects.

**Comment by moltob** [comment]
Don't worry about all the communication stuff. I'm happy you take the contributions. :-)

I have finished the deployment of pymultigen to travis, coveralls and pypi, added badges and set it up that a Github release tag will eventually upload the wheel to PyPI. Could be interesting for the other projects as well?

For my project, I did not use tox, since travis already does the matrix build for the different Python runtimes. Instead I am using ``python setup.py test`` which is a way to test a distribution and observe the ``tests_require`` attribute in setup.

Feel free to copy any setup from pymultigen or aks me to set it up. Whatever you like. pyecoregen is also prepared to allow test execution via ``setup.py`` or ``py.test``. But of course, use tox if you prefer.

Let me know if something is missing. Once you or I set up pyecoregen in PyPI I'll publish the PR against pyecore's develop branch.

TTYS,
Mike

**Comment by moltob** [comment]
Fyi: open todos in the two generator projects include docs and test coverage. I'll also want to add the CLI script to pyecoregen as discussed. But I think we can prerelease just fine. Also I'll go ahead with the pyecoregen PR since it simply removes pygen and does not depend on any new code. Pyecoregen depends on pyecore and pymultigen...

**Comment by aranega** [comment]
Sorry for the late answer, lately I have some issues with my wifi and my internet access.

That's a real good news that the pymultigen is on pypi! Indeed, the automatic deployment from Travis to pypi is very interesting, I will check your config files to see how you've done this. Thanks for the tip, this will save me a lot of time :-). Do you know if this is possible to activate the deployment only for the `master` branch?

I saw that you didn't used tox. This is totally fine with me, I mainly configured tox to be able to easily run `flake8` after `pytest` in local, and mainly because it is quicker to write than `python setup.py test` :-). 

I'm merging your PR right away and I will also add 'coveralls' configuration as you've done in your project, as well as.

Regarding the communication stuffs, I prefer crediting you if that's ok with you (I will be more confortable) as you've really done a lot for the project. Again, thanks a lot!

**Comment by moltob** [comment]
Perfect. I think we can close the ticket then. I'll write docs, increase coverage and do the CLI script.

**Comment by aranega** [comment]
Great! I'm closing the ticket. Mike, thanks so much for your contribution, be sure I really appreciate.

**Comment by moltob** [comment]
I've raised test coverage of pymultigen and pyecoregen into green levels and wrote docs. That should be it for now. I've released a new version of multigen yesterday, feel free to release pyecoregen with CLI support, see the docs for how to use.

There are smaller improvements and extensions coming up, but the current state should work for many usecases.

**Comment by aranega** [comment]
Great! That's really awesome! I'm pushing the new version of pyecoregen to pypi. In the same occasion, I performed a small modification on pyecoregen, I removed the loaded metamodel registration from the `ResourceSet` as it is not required (since no instance of the loaded metamodel are read). I hope you don't mind, I didn't go through a PR for this modification in order to push the first full version quickly. The other modifications I will perform (if there is any), I will submit them via PR for you to review them in a first place.

I think I will (try) to communicate today about pymultigen, pyecoregen and the new version of pyecore. Since more people can be interested in pymultigen (way more than pyecore), perhaps it could be a good idea for you to push something on hackernews or reddit? I'm not used to use these, so I could be mistaken.

**Comment by moltob** [comment]
You certainly don't have to go through a PR :-) Consider pyecoregen my contribution to your project. I'll take a look at hackernews to see whether that could make sense. Haven't used it so far...

**Comment by moltob** [comment]
Tried reddit...

https://www.reddit.com/r/Python/comments/6dgyhj/multifile_code_generation_with_singlefile_engines/?ref=share&ref_source=link

We'll see.

**Comment by aranega** [comment]
Thank you so much Mike for the contribution. I'm playing with it a lot, I was trying to generate the XMLTypes datatypes and stuffs, and I realize that I totally missed the `EDatatye` generation in the Acceleo generator. I think this will be the next pyecoregen feature, it will help me to make my first big modification.

I tweeted about pymultigen and upvoted the reddit post. I hope you will have positive comments! I will also tweet later about it, regarding the time of the day the activity can be very different.
